### Get estimate 
GET http://localhost:3000/reports?make=Lambourghini&model=Veyron&madeYear=2027&mileage=30&lat=40&lng=45


### Creates a new report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Lambourghini",

  "model": "Veyron",
  
  "madeYear": 2027,

  "soldPrice": 80000,

  "mileage": 30,

  "lat": 45,

  "lng": 45
}

### Approves an existing report
PATCH http://localhost:3000/reports/6
content-type: application/json

{
  "approved": true
}
