### Creates a new report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Porch",

  "model": "Pantara",
  
  "madeYear": 2025,

  "soldPrice": 50000,

  "mileage": 0,

  "lat": "40.7128",

  "lng": "-74.0060"
}
